
<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-gear"></i> Telemática
    </li>

    <li class="active">
        <i class="fa fa-linux"></i> Area de soporte de equipos tecnológicos
    </li>

    <li class="active">
        <i class="fa fa-users"></i> Funcionarios 
    </li>
</ol>


 <div id="page-wrapper">
	<div class="container">
		<div class="col-md-12 col-md-offset-0" >
            <div class= "panel panel-primary">
	 			<div class="panel-body">
					<div class="dataTable_wrapper">
	 					<form action="<?php  echo BASE_URL;?>telematica/consulta" method="post">
	 						<table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                        <tr>                                        	
                                            <th>Cedula</th>
                                            <th>Credencial</th>                    
                                            <th>Nombre y Apellido del Funcionario</th>                                            
                                            <th>Acciones</th>                         

                                        </tr>
                                    </thead>                                 
                                    <tbody>
                             <?php foreach ($this->_lista as $persona): ?>

                                <tr class="info">                                   
                                    <td align="center"><?php echo $persona['cedula'];?></td>
                                    <td align="center"><?php echo $persona['credencial'];?></td>
                                    <td align="center">
                                        <?php echo $persona['nombre_1'];?>
                                        <?php echo $persona['apellido_1'];?>
                                    </td>
                                    
                                    <td align="center">

                                <?php  if(session::get('level')==('Super Usuario Telematica')):?>
           								<a href="<?php echo BASE_URL."telematica/ticket_jn/". $persona['id'] ; ?>">
                                            <span title="Crear Nuevo Requerimiento" class="fa fa-file-text"></span>
                                        </a>
                                <?php  endif;?> 

                                <?php  if(session::get('level')==('Usuario Telematica')):?>
                                        <a href="<?php echo BASE_URL."telematica/ticket/". $persona['id'] ; ?>">
                                            <span title="Crear Nuevo Requerimiento" class="fa fa-file-text"></span>
                                        </a>
                                <?php  endif;?> 
                                
                                    </td>


                                </tr>

                            <?php endforeach ?>
                                    </tbody>
                                </table>

                        <?php  if(session::get('level')==('Super Usuario Telematica')):?>  
                            <a href="<?php echo BASE_URL."telematica/nuevo_ticket_jn/"?>">
                                <span title="Crear Nuevo Requerimiento">¿No encuentra al funcionario?</span>
                            </a>
                        <?php  endif;?>

                        <?php  if(session::get('level')==('Usuario Telematica')):?>  
                            <a href="<?php echo BASE_URL."telematica/newticket/"?>">
                                <span title="Crear Nuevo Requerimiento">¿No encuentra al funcionario?</span>
                            </a>
                        <?php  endif;?>                        
                        
	 		 			</form>
	 				</div>
	 			</div>
            </div>                    
 		</div>
 	</div>
</div>	 	

 <br><br>
<br><br>
<br>
