<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-gear"></i> Telemática
    </li>

    <li class="active">
        <i class="fa fa-desktop"></i> Área de servicio
    </li>

    <li class="active">
        <i class="fa fa-edit"></i> Mis Requerimientos Asigandos
    </li>
</ol>

     <div id="page-wrapper">
        <div class="container">
            <div class="col-md-12 col-md-offset-0" >
                <div class= "panel panel-primary">
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                     
                            <form action="<?php  echo BASE_URL;?>micro/mis_req_aserv" method="post">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                        <thead>
                                            <tr>
                                            	<th>Resgistro</th>
                                                <th>Cred. Solicitante</th>
                                                <th>Dependencia</th>
                                                <th>Analista</th>

                                                <th>Inicio</th>                                                   
                                                <th>culminacion</th>
                                                <th>Status</th>                                                
                                                <th>Acciones</th>
                           

                                            </tr>
                                        </thead>                                 
                                        <tbody>
                                <?php foreach ($this->_lista as $requerimiento): ?>
                                    <tr class="info"> 

                                    	<td align="center"><?php echo $requerimiento['id']; ?></td>

                                        <td align="center"><?php echo $requerimiento['credencial'];?></td>

                                        <td align="center"><?php echo $requerimiento['descripcion_depen'];?></td>
                                        
                                        <td align="center"><?php echo $requerimiento['analista'];?></td>                                       

                                        <td align="center"><?php echo $requerimiento['fecha_inicio'];?></td>                                                              

                                                              
                                        <td align="center"><?php echo $requerimiento['fecha_culminacion'];?></td>

                                        <td align="center"><?php echo $requerimiento['status_caso'];?></td>                                                                             
                                        

                                        <td align="center">

                                        <a href="<?php echo BASE_URL."telematica/updatesoporte/". $requerimiento['id'] ; ?>">
                                            <span title="Editar Requerimiento" class="glyphicon glyphicon-edit"></span>                       
                                        </a>

                                           &nbsp;                                                                                     
                                        <a href="<?php ECHO BASE_URL."telematica/pdfsoporte/". $requerimiento['id'] ; ?>">
                                            <span title="Imprimir Ticket de Salida" class="glyphicon glyphicon-save"></span>                     
                                        </a>                                        

                                            
                                        </td>
                                       

                                    </tr>
                                <?php endforeach ?>
                                        </tbody>
                                </table>
                            </form>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>      

    <br><br>
    <br><br>

    