<ol class="breadcrumb">
    <li>
        <i class="fa fa-home">
        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a></i>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>

    <li class="active">
        <i class="fa fa-gear"></i> Telemática
    </li>

    <li class="active">
        <i class="fa fa-linux"></i> Área de soporte de equipos tecnológicos
    </li>

     <li class="active">
        <i class="fa fa-user"></i>

        <?php  if (isset($_view_params['menu10'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu10']); $i++):?>         
        <a href="<?php  echo $_view_params['menu10'][$i]['link'];?>"><?php  echo $_view_params['menu10'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>        

    <li class="active">
        <i class="fa fa-file-text"></i> Levantar Requerimiento
    </li>
</ol>

<body>
     <header class="header">
    <div class= "row ">
        <div class="col-md-10 col-sm-offset-1" >
      <form id="micro" class="form-horizontal" action="<?php  echo BASE_URL;?>telematica/newticket" method="post">

        <div class= "panel panel-primary" >
          <div class= "panel-heading" >
            <h3 class= "panel-title fa fa">Datos del Solicitante</h3>
          </div>
              
          <div class="panel-body">


          <div class="form-group">
            
            <div class="col-sm-3 col-sm-offset-0" class="" id="cedula2">
                 <strong><p id="cedula1"></p></strong>
              </div>

            <div class="col-sm-4 col-sm-offset-0" class="" id="credencial2">
                <strong><p id="credencial1"></p></strong>
            </div>  

          </div>
          
          <div class="form-group">
            <label class="col-sm-1 col-md-offset-0">Cedula</label>
            <label class="col-sm-2 col-md-offset-2">Credencial</label>
            <label class="col-sm-3 col-md-offset-1">Primer Nombre</label>
            <label class="col-sm-2 col-md-offset-0">Segundo Nombre</label>
          </div>

          <div class="form-group">
  
            
              <div class="col-sm-3 col-sm-offset-0">                
                  <input type="text" class="form-control" name="cedula" placeholder="Ej. 10111233" id="cedula" title="Cedula">                    
              </div>

              <div class="col-sm-3 col-sm-offset-0">                
                  <input type="text" class="form-control" name="credencial" placeholder="Ej. 10111" id="credencial" title="credencial">                     
              </div>
            
              <div class="col-sm-3 col-sm-offset-0">            
                <input type="text" class="form-control"  name="nombre_1" " placeholder="Ej. Rafael" title="nombre_1" >  
              </div>
            
              <div class="col-sm-3 col-sm-offset-0">              
                <input type="text" class="form-control"  name="nombre_2"  placeholder="Ej. Jose" title="nombre_2" >
              </div>              

          </div>        
          
          <div class="form-group">

            <label class="col-sm-3 col-md-offset-0">Primer Apellido</label>
            <label class="col-sm-2 col-md-offset-0">Segundo Apellido</label>            
            <label class="col-sm-1 col-md-offset-1">Cargo</label>           
            <label class="col-sm-2 col-md-offset-2">Jerarquia</label>

          </div>

                    
                  

          <div class="form-group">

            <div class="col-sm-3 col-md-offset-0">
              <input type="text" class="form-control"  name="apellido_1" placeholder="Ej. Lopez" title="apellido_1" >   
            </div>
          
            <div class="col-sm-3 col-md-offset-0">            
              <input type="text" class="form-control"  name="apellido_2"  placeholder="Ej. Dominguez" title="apellido_2" >
            </div>

            <div class="col-sm-3 col-md-offset-0">
              <input type="text" class="form-control"  name="cargo"  placeholder="Ej. Analista Contable" title="Cargo" >
            </div>
          
            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control"  name="jerarquia"  id="jerarquia" title="jerarquia" >
                  <option>Seleccione...</option>                  
                </select>
            </div>              
          </div>          

          <div class="form-group">
          
            <label class="col-sm-5">correo electronico</label>

          </div>

          <div class="form-group">

            <div class="col-sm-3">
              <input type="text"  class="form-control" name="correo"  placeholder="Ej. adominguez@gmail.com" title="Correo">
            </div>

          </div>

          </div>
        </div>

        <div class= "panel panel-primary" >
          <div class= "panel-heading" >
            <h3 class= "panel-title fa fa">Datos del Despacho</h3>
          </div>              
          <div class="panel-body">

          <div class="form-group">
            <label class="control-label col-sm-4 col-md-offset-0">Direccion</label>
          
          </div>  

          <div class="form-group">

              <div class="col-sm-4">
                <select class="form-control"  name="areaa" id="areaa">
                  <option>Seleccione...</option>
                </select>               
              </div>

              <div class="col-sm-4">
                <select class="form-control"  name="areab" id="areab">
                  <option>Seleccione...</option>                    
                </select>               
              </div>

              <div class="col-sm-4">
                <select class="form-control"  name="areac" id="areac">
                  <option>Seleccione...</option>                  
                </select>               
              </div>              
          </div>  
          <div class="form-group">
            <div>
              <label class="col-sm-2 col-md-offset-2">Codigo de area</label>
            </div>

            <div>
              <label class="col-sm-2 col-md-offset-2">Numero de contacto</label>
            </div>
          </div>

          <div class="form-group">
            
              <div class="col-sm-3 col-md-offset-2">
                <select class="form-control"  name="cod_area" id="cod_area">
                  <option>Seleccione...</option>                  
                </select>
              </div>
              <div class="col-sm-3 col-md-offset-1">  
                  <input type="text" class="form-control" name="numero_tel_requerimiento" placeholder="Ej. 8963214" title="numero de telefono">   
              </div>
          </div>                      
      
          </div>
        </div>

        <div class= "panel panel-primary" >
          <div class= "panel-heading">
            <h3 class= "panel-title">Datos Del Requerimiento</h3>
          </div>
              
          <div class="panel-body">

          <div class="form-group">

            <label class="col-sm-3 col-md-offset-0">Tipo de Equipos</label>
            <label class="col-sm-2 col-md-offset-0">Marca del Equipo</label>            
            <label class="col-sm-2 col-md-offset-1">Modelo del Equipo</label>           
            <label class="col-sm-2 col-md-offset-1">Serial del equipo</label>

          </div>   

          <div class="form-group">

            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control" name="tipo_equipo" id="tipo_equipo" onChange="selectequipo(this)">
                  <option>Seleccione...</option>
                </select>            
            </div>
          
            <div class="col-sm-3 col-md-offset-0">            
                <input type="text" class="form-control" id="marca_del_equipo" name="marca_del_equipo"  placeholder="Marca del equipo" title="marca del equipos" >               
            </div>

            <div class="col-sm-3 col-md-offset-0">
                      <input type="text" class="form-control" name="modelo_del_equipo" placeholder="Modelo del Equipo" id="modelo_del_equipo" title="Modelo del Equipo">   
            </div>
          
            <div class="col-sm-3 col-md-offset-0">
                <input type="text" class="form-control"  name="serial_del_equipo" id="serial_del_equipo"  placeholder="serial del equipo" title="serial_del_equipo" >   
            </div>

          </div>   

          <div class="form-group">

            <label class="col-sm-3 col-md-offset-0">Pieza Dañada</label>
            <label class="col-sm-2 col-md-offset-0">Rayado</label>            
            <label class="col-sm-2 col-md-offset-1">Pieza Suelta</label>
            <div id="mp" style="display:none;">       
            <label class="col-sm-2 col-md-offset-1" >Marca del Procesador</label>
            </div>
          </div> 

          <div class="form-group">

            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control" title="¡Si su respuesta es afirmativa, por favor detallar en la descripción, la pieza que se encuentra dañada!" name="pieza_danada" id="pieza_danada">
                <option>Seleccione...</option>
                </select>          
            </div>
          
            <div class="col-sm-3 col-md-offset-0">            
                <select class="form-control" title="¡Si su respuesta es afirmativa, por favor detallar en la descripción, la pieza que se encuentra Rayada!" name="rayado" id="rayado">
                <option>Seleccione...</option>
                </select>               
            </div>

            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control"  title="¡Si su respuesta es afirmativa, por favor detallar en la descripción, la pieza que se encuentra suelta!" name="pieza_suelta" id="pieza_suelta">
                  <option>Seleccione...</option>                      
                </select>   
            </div>
          
            <div class="col-sm-3 col-md-offset-0" id="mr" style="display:none;">
                    <select class="form-control" title="¡POR FAVOR describir el modelo del procesador en la descripcion!" name="marca_procesador" id="marca_procesador">
                    <option value="143">Seleccione...</option>
                    </select>  
            </div>

          </div> 
   

          <div class="form-group">
            <div id="mpp" style="display:none;">
            <label class="col-sm-3 col-md-offset-0">Tipo de RAM</label>
            <label class="col-sm-2 col-md-offset-0">Capacidad de RAM</label> 
            <label class="col-sm-2 col-md-offset-1">Cantida de memorias ram</label>           
            <label class="col-sm-2 col-md-offset-1">Tipo de Disco Duro</label>
            </div>
          </div>

          <div class="form-group">
            <div id="mr1" style="display:none;">
            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control" name="tipo_de_ram" id="tipo_de_ram">
                <option value="101">Seleccione...</option>
                </select>       
            </div>
          
            <div class="col-sm-3 col-md-offset-0">            
                <select class="form-control" name="capacidad_ram" id="capacidad_ram">
                <option value="122">Seleccione...</option>
                </select>             
            </div>
            <div class="col-sm-3 col-md-offset-0">
                  <input type="number" class="form-control" name="cantidad_memoria_ram" placeholder="cantidad de memoria ram" id="cantidad_memoria_ram" title="Especifique la cantidad de memoria ram que posee el equipo" >
            </div>
          
            <div class="col-sm-3 col-md-offset-0">
                <select class="form-control" name="tipo_disco_duro" id="tipo_disco_duro">
                <option value="111">Seleccione...</option>
                </select>
            </div>
            </div>
          </div> 

          <div class="form-group">
            <div id="dd" style="display:none;">
              <label class="col-sm-3 col-md-offset-0">Capacidad de almacenamiento</label>
              <label class="col-sm-2 col-md-offset-0">Cantida de Discos Duro</label>            

              <label class="col-sm-2 col-md-offset-1">Fancooler</label>           
              <label class="col-sm-3 col-md-offset-1">Unidad de DVD/CD-ROM</label>
           </div>
          </div>

          <div class="form-group">
              
              <div id="cp1" style="display:none;">
              <div class="col-sm-3 col-md-offset-0">
                  <select class="form-control" name="capacidad_disco_duro" id="capacidad_disco_duro">
                  <option value="139">Seleccione...</option>
                  </select>      
              </div>          
              <div class="col-sm-3 col-md-offset-0">            
                  <input type="number" class="form-control" name="cantidad_disco_duro" placeholder="cantida de disco duro" id="cantidad_disco_duro" title="Especifique la cantidad de discos duro que posee el equipo" >            
              </div>
              <div class="col-sm-3 col-md-offset-0">
                  <input type="number" class="form-control" name="fan_cooler" placeholder="cantidad de fancooler internos" id="fan_cooler" title="Especifique la cantidad de fancooler internos del equipo" >
              </div>          
              <div class="col-sm-3 col-md-offset-0">
                  <input type="number" class="form-control" name="unidad_dvd_cd" placeholder="cantidad de unidad de dvd/dc instaladas" id="unidad_dvd_cd" title="Especifique la cantidad de unidad de DVD/CD instaladas" >
              </div>
              </div>              

          </div>  

          <div id="cp2" style="display:none;">
          <div class="form-group">

              <label class="col-sm-3 col-md-offset-0">Tarjeta de Red</label>
              <label class="col-sm-2 col-md-offset-0">Tarjeta de Video</label>    
              <label class="col-sm-2 col-md-offset-1">Tarjeta de Sonido</label>              
        
          </div>

          <div class="form-group">            
            
              <div class="col-sm-3 col-md-offset-0">
                  <input type="number" class="form-control" name="tarjeta_red" placeholder="cantidad de tarjeta de Red interna" id="tarjeta_red" title="tarjeta de red" >    
              </div>          
              <div class="col-sm-3 col-md-offset-0">            
                  <input type="number" class="form-control" name="tarjeta_video" placeholder="cantidad de tarjeta de video interna" id="tarjeta_video" title="tarjeta de video" >          
              </div>
              <div class="col-sm-3 col-md-offset-0">
                  <input type="number" class="form-control" name="tarjeta_sonido" placeholder="cantidad de tarjeta de sonido interna" id="tarjeta_sonido" title="tarjeta de sonido" >
              </div>          


          </div>                                                              
          </div>

          <div class="form-group">
              <label class="col-sm-3 col-md-offset-0">Descripción</label>            
          </div>


          <div class="form-group">            
            
              <div class="col-sm-12 col-md-offset-0">
                  <div class="col-sm-12">
                    <textarea type="text" class="form-control" name="descripcion" placeholder="Max 500 Caracteres." maxlength="500" id="descripcion" class=estilotextarea1 cols="60" rows="2"></textarea>        
                  </div>  
              </div>          
        


          </div>             

                <div class="col-sm-5">
                  <input type="hidden" value="163" class="form-control" name="status_equipo" id="status_equipo">
                </div>              

            <div class="col-sm-offset-6">
              <input type="submit" value="Registrar" class="btn btn-primary" onclick="return confirm('¿Esta seguro que desea registrar este requerimiento?');">
            </div>
            
          </div>
        </div>
        
    
        </form> 
      </div>
    </div>
  </header>
</body>
</html>