<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-gear"></i> Telemática
    </li>

    <li class="active">
        <i class="fa fa-desktop"></i> Área de servicio
    </li>    

    <li class="active">
        <i class="fa fa-edit"></i> Requerimientos General
    </li>
</ol>

     <div id="page-wrapper">
        <div class="container">
            <div class="col-md-10 col-md-offset-1" >
                <div class= "panel panel-primary">
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <form action="<?php  echo BASE_URL;?>telematica/reportesmicro" method="post">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                        <thead>
                                            <tr>
                                            	<th>N° de Ticket</th>
                                                <th>Analista </th>
                                                <th>Inicio</th>                                                   
                                                <th>culminacion</th> 
                                                    
                                               

                                                <th>Acciones</th>
                           

                                            </tr>
                                        </thead>                                 
                                        <tbody>
                                <?php foreach ($this->_lista as $requerimiento): ?>
                                    <tr class="info"> 

                                    	<td align="center"><?php echo $requerimiento['id']; ?></td> 

                                        <td align="center">
                                        <?php echo $requerimiento['nombre_1'];?>
                                        <?php echo $requerimiento['apellido_1'];?>
                                        </td>
                                        <td align="center"><?php echo $requerimiento['fecha_micro'];?></td>                                                              
                                        <td align="center"><?php echo $requerimiento['fecha_entrega'];?></td>
                                        

                                        <td align="center">
                                            

                                        <a href="<?php echo BASE_URL."telematica/viewrequerimiento/". $requerimiento['id'] ; ?>">
                                            <span title="Ver Requerimiento" class="glyphicon glyphicon-eye-open"></span>                                         
                                        </a>
                                            &nbsp; 
                                        <a href="<?php echo BASE_URL."telematica/updaterequerimiento/". $requerimiento['id'] ; ?>">
                                            <span title="Editar Requerimiento" class="glyphicon glyphicon-edit"></span>                                         
                                        </a>

                                           &nbsp; 
                                        <a href="<?php ECHO BASE_URL."telematica/delete/". $requerimiento['id'] ; ?>">
                                        <span onclick=" return confirm('¿Esta seguro que desea eliminar a este requerimiento?');" title="Eliminar requerimiento" class="glyphicon glyphicon-trash"></span>                                         
                                        </a> 
                                           &nbsp;                                                                                     
                                        <a href="<?php ECHO BASE_URL."telematica/pdf/". $requerimiento['id'] ; ?>">
                                            <span title="Descargar en PDF" class="glyphicon glyphicon-save"></span>                                         
                                        </a>

                                            
                                        </td>
                                       

                                    </tr>
                                <?php endforeach ?>
                                        </tbody>
                                </table>
                            </form>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>      

    <br><br>
    <br><br>

    