<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-gear"></i> Telemática
    </li>

    <li class="active">
        <i class="fa fa-linux"></i> Área de soporte de equipos tecnológicos
    </li>

    <li class="active">
        <i class="fa fa-edit"></i> Requerimientos Generales
    </li>
</ol>

     <div id="page-wrapper">
        <div class="container-fluid">
            <div class="col-md-12 col-md-offset-0" >
                <div class= "panel panel-primary">
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                     
                            <form action="<?php  echo BASE_URL;?>micro/rtelecargados" method="post">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                        <thead>
                                            <tr>
                                            	<th>Ticket:</th>
                                                <th>C.I Solicitante</th>
                                                <th>Dependencia</th>
                                                <th>Tecnico</th>
                                                <th>Inicio</th>                                                   
                                                <th>culminacion</th>
                                                <th>Status </th>
                                                <th>Acciones</th>
                           

                                            </tr>
                                        </thead>                                 
                                        <tbody>
                                <?php foreach ($this->_lista as $requerimiento): ?>
                                    <tr class="info"> 

                                    	<td align="center"><?php echo $requerimiento['id']; ?></td>

                                        <td align="center"><?php echo $requerimiento['cedula'];?></td>

                                        <td align="center"><?php echo $requerimiento['descripcion_depen'];?></td>                                      
                                        <td align="center"><?php echo $requerimiento['tecnico'];?></td>                                        

                                        <td align="center"><?php echo $requerimiento['fecha_micro'];?></td>                                                              
                                        <td align="center"><?php echo $requerimiento['fecha_entrega'];?></td>

                                        <td align="center"><?php echo $requerimiento['status_equipo'];?></td>                                        
                                        

                                        <td align="center">
                                            

<!--                                         <a href="<?php echo BASE_URL."telematica/vrmicro/". $requerimiento['id'] ; ?>">
                                            <span title="Ver Requerimiento" class="glyphicon glyphicon-eye-open"></span>                          
                                        </a>

                                            &nbsp;  -->

                                        <?php  if(session::get('level')==('Super Usuario Telematica')):?>  
                                            &nbsp; 
                                            <a href="<?php echo BASE_URL."telematica/urmicro/". $requerimiento['id'] ; ?>">
                                                <span title="Editar Requerimiento" class="glyphicon glyphicon-edit"></span>                       
                                            </a>
                                        <?php  endif;?>                                            


                                        <?php  if(session::get('level')==('Super Usuario Telematica')):?>  
                                            &nbsp; 
                                            <a href="<?php echo BASE_URL."telematica/aticket/". $requerimiento['id'] ; ?>">
                                                <span title="Asignar Ténico" class="glyphicon glyphicon-user"></span>                             
                                            </a>
                                        <?php  endif;?>

                                        <?php  if(session::get('level')==('Super Usuario Telematica')):?>  
                                           &nbsp; 
                                        <a href="<?php ECHO BASE_URL."telematica/delete/". $requerimiento['id'] ; ?>">
                                        <span onclick=" return confirm('¿Esta seguro que desea eliminar a este requerimiento?');" title="Eliminar requerimiento" class="glyphicon glyphicon-trash"></span>                                         
                                        </a>
                                           &nbsp;                                          
                                        <?php  endif;?>
                                                                                  
                                        <a href="<?php ECHO BASE_URL."telematica/pdfentrada/". $requerimiento['id'] ; ?>">
                                            <span title="Imprimir Ticket de Entrada" class="glyphicon glyphicon-open"></span>                     
                                        </a>

                                           &nbsp;                                                                                     
                                        <a href="<?php ECHO BASE_URL."telematica/pdfsalida/". $requerimiento['id'] ; ?>">
                                            <span title="Imprimir Ticket de Salida" class="glyphicon glyphicon-save"></span>                     
                                        </a>                                        


                                            
                                        </td>
                                       

                                    </tr>
                                <?php endforeach ?>
                                        </tbody>
                                </table>
                            </form>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>      

    <br><br>
    <br><br>

    