<div class="container">
    <u><b><h4 align="center">Bienvenido</u></b></h4>
    <u><b><h4 align="center">Sistema para el Registro y Control de Requerimientos</u></b></h4>
</div>

<hr id="separacion">
<div class="container">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-4 col-md-9">
             <img id="logo" src="<?php echo PUBLIC_URL; ?>img/avatar6.png" height="350">
        </div>
    </div>
</div>


<hr id="separacion">
