<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-user"></i> Gestion de Usuarios
    </li>

    <li class="active">
        <i class="fa fa-edit"></i> Funcionarios 
    </li>
</ol>


 <div id="page-wrapper">
	<div class="container">
		<div class="col-md-12 col-md-offset-0" >
            <div class= "panel panel-primary">
	 			<div class="panel-body">
					<div class="dataTable_wrapper">
	 					<form action="<?php  echo BASE_URL;?>persons/consulta" method="post">
	 						<table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                        <tr>                                            
                                            <th>Cedula</th>
                                            <th>Credencial</th>                    
                                            <th>Nombre y Apellido del Funcionario</th>              
                                            <th>Cargo</th> 
                                            <th>Jerarquia</th>
                                            <th>Dependencia</th>                                          
                                            <th>Acciones</th>                  

                                        </tr>
                                    </thead>                                  
                                    <tbody>
                            <?php foreach ($this->_listado as $persona): ?>
                                <tr class="info">                                   
                                    <td align="ceneter"><?php echo $persona['cedula'];?></td>
                                    <td align="center"><?php echo $persona['credencial'];?></td>
                                    <td align="center">
                                        <?php echo $persona['nombre_1'];?>
                                        <?php echo $persona['apellido_1'];?>
                                    </td>                                                                 
                                    <td align="center"><?php echo $persona['cargo'];?></td>
                                    <td align="ceneter"><?php echo $persona['jerarquia'];?></td>
                                    <td align="ceneter"><?php echo $persona['descripcion_depen'];?></td>                  
                                    <td align="center">
                                    	
           								<a href="<?php echo BASE_URL."persons/update/". $persona['id'] ; ?>">
                                            <span title="Editar Datos de Funcionario" class="glyphicon glyphicon-edit"></span>                                         
                                       </a>
                                       &nbsp; 
<!--                                         <a href="<?php echo BASE_URL."persons/delete/". $persona['id'] ; ?>">
                                            <span onclick=" return confirm('¿Esta seguro que desea eliminar a este usuario?');" title="Eliminar Usuario" class="glyphicon glyphicon-trash"></span>
                                        </a> -->
                                       &nbsp; 
                                        <a href="<?php echo BASE_URL."persons/asign/". $persona['id'] ; ?>">
                                            <span title="Asignar Usuario" class="glyphicon glyphicon-user"></span>
                                        </a>                                        
                                    </td>
                                </tr>
                            <?php endforeach ?>
                                    </tbody>
                                </table>
                            <a href="<?php echo BASE_URL."persons/insert/"?>">
                                <span title="Crear Nuevo Requerimiento">¿No encuentra al funcionario?</span>                                         
                            </a>

	 		 			</form>


	 				</div>
	 			</div>
            </div>                    
 		</div>
 	</div>
</div>	 	

 <br><br>
<br><br>
<br>