<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-user"></i> Gestion de Usuarios
    </li>

    <li class="active">
        <i class="fa fa-edit"></i> Usuarios del SISRCOR 
    </li>
</ol>


     <div id="page-wrapper">
		<div class="container">
			<div class="col-md-12 col-md-offset-0" >
                <div class= "panel panel-primary">
    	 			<div class="panel-body">
    					<div class="dataTable_wrapper">
    	 					<form action="<?php  echo BASE_URL;?>persons/consultauser" method="post">
    	 						<table class="table table-striped table-bordered table-hover" id="dataTables">
                                        <thead>
                                            <tr>
                                                <th>Credencial</th>                                      	
                                                <th>Nombre:</th>                 
                                                <th>Nombre de usuario</th>
                                                <th>Dependencia</th>                                         
                                                <th>Perfil</th>                                          
                                                <th>Editar</th>                          

                                            </tr>
                                        </thead>                                 
                                        <tbody>
                                <?php foreach ($this->_lista as $usuario): ?>
                                    <tr class="info">                                   
                                        
                                        <td align="center"><?php echo $usuario['credencial'];?></td>
                                        <td align="center"><?php echo $usuario['usuario_siscor'];?></td>
                                        <td align="center"><?php echo $usuario['usuario'];?></td>
                                        <td align="center"><?php echo $usuario['descripcion_depen'];?></td>       
                                        <td align="ceneter"><?php echo $usuario['perfil'];?></td>
                                       
                                        <td align="center">                                    	
               								<a href="<?php echo BASE_URL."persons/updateusuario/". $usuario['id'] ; ?>">
                                                <span title="Editar Perfil" class="glyphicon glyphicon-user"></span>                                         
                                            </a>
                                            &nbsp;
                                        <a href="<?php echo BASE_URL."persons/update/". $usuario['pid'] ; ?>">
                                            <span title="Editar datos basicos del Usuario" class="glyphicon glyphicon-edit"></span>                                         
                                       </a>
                                       &nbsp; 
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                                        </tbody>
                                    </table>
    	 		 			</form>


    	 				</div>
    	 			</div>
                </div>             
	 		</div>
	 	</div>
	</div>	 	

            <br><br>
        <br><br>
    <br><br>
<br><br><br>
