<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-user"></i> Gestion de Usuarios
    </li>

	

    <li class="active">
        <i class="fa fa-edit"></i> Actualizacion de datos
</ol>

<body>
     <header class="header">
		<div class="row">
		    <div class="col-md-12" >
		    	<form  id="personuser" class="form-horizontal" action="<?php  echo BASE_URL;?>persons/update "	method="post">
	        				<input type="hidden" name="id"  value="<?php echo $this->_persona[0]['id'] ?>" >
		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa">Datos del Solicitante</h3>
		 			</div>
							
		 			<div class="panel-body">


					<div class="form-group">
						
						<div class="col-sm-3 col-sm-offset-0" class="" id="cedula2">
	   						 <strong><p id="cedula1"></p></strong>
	   					</div>

						<div class="col-sm-4 col-sm-offset-0" class="" id="credencial2">
						 		<strong><p id="credencial1"></p></strong>
						</div>	

					</div>
					
					<div class="form-group">
						<label class="col-sm-1 col-md-offset-0">Cedula</label>
						<label class="col-sm-2 col-md-offset-2">Credencial</label>
						<label class="col-sm-3 col-md-offset-1">Primer Nombre</label>
						<label class="col-sm-2 col-md-offset-0">Segundo Nombre</label>
					</div>

					<div class="form-group">
	
						
							<div class="col-sm-3 col-sm-offset-0">								
										<input type="text" class="form-control" name="cedula" placeholder="Cedula" id="cedula" title="Cedula" value="<?php echo $this->_persona[0]['cedula'] ?>">									
							</div>

							<div class="col-sm-3 col-sm-offset-0">								
										<input type="text" class="form-control" name="credencial" placeholder="Credencial" id="credencial" title="credencial" value="<?php echo $this->_persona[0]['credencial'] ?>">											
							</div>
						
							<div class="col-sm-3 col-sm-offset-0">						
								<input type="text" class="form-control" name="nombre_1" placeholder="Primer Nombre" title="nombre_1" value="<?php echo $this->_persona[0]['nombre_1'] ?>">		
							</div>
						
							<div class="col-sm-3 col-sm-offset-0">							
								<input type="text" class="form-control" name="nombre_2" placeholder=" Segundo Nombre" title="nombre_2" value="<?php echo $this->_persona[0]['nombre_2'] ?>">
							</div>							

					</div>				
					
					<div class="form-group">

						<label class="col-sm-3 col-md-offset-0">Primer Apellido</label>
						<label class="col-sm-2 col-md-offset-0">Segundo Apellido</label>						
						<label class="col-sm-1 col-md-offset-1">Cargo</label>						
						<label class="col-sm-2 col-md-offset-2">Jerarquia</label>

					</div>

										
							    

					<div class="form-group">

						<div class="col-sm-3 col-md-offset-0">
								<input type="text" class="form-control" name="apellido_1" placeholder="Primer apellido" title="apellido_1" value="<?php echo $this->_persona[0]['apellido_1'] ?>">		
						</div>
					
						<div class="col-sm-3 col-md-offset-0">						
								<input type="text" class="form-control" name="apellido_2" placeholder=" Segundo apellido" title="apellido_2" value="<?php echo $this->_persona[0]['apellido_2'] ?>">
						</div>

						<div class="col-sm-3 col-md-offset-0">
								<input type="text" class="form-control" name="cargo" placeholder="cargo" title="cargo" value="<?php echo $this->_persona[0]['cargo'] ?>">
						</div>
					
						<div class="col-sm-3 col-md-offset-0">
								<select class="form-control"  name="jerarquia" id="jerarquia">
									<option value="<?php echo $this->_persona[0]['jid'] ?>" ><?php echo $this->_persona[0]['jerarquia'] ?></option>									
								</select>
						</div>							
					</div>					

					<div class="form-group">
					
						<label class="col-sm-5">correo electronico</label>

					</div>

					<div class="form-group">

						<div class="col-sm-3">

									<input type="text" class="form-control" name="correo" placeholder="Ingrese un correo" title="correo" value="<?php echo $this->_persona[0]['correo'] ?>">
						</div>

					</div>

		 			</div>
		 		</div>



				<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa"> Despacho</h3>
		 			</div>		 					
		 			<div class="panel-body">


					<div class="form-group">

							<div class="col-sm-4">
								<select class="form-control"  name="areaa" id="areaa"  >
									<option value="<?php echo $this->_persona[0]['pdi'] ?>"><?php echo $this->_persona[0]['padre_padre'] ?></option>
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areab" id="areab" >
									<option value="<?php echo $this->_persona[0]['abid'] ?>"><?php echo $this->_persona[0]['padre_despacho'] ?></option>										
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areac" id="areac"  >
									<option value="<?php echo $this->_persona[0]['aid'] ?>"><?php echo $this->_persona[0]['areac']?></option>				
								</select>								
							</div>


					</div>				
			
							<div class="col-sm-offset-6">
								<input type="submit" value="Registrar" class="btn btn-primary" onclick=" return confirm('¿Estas seguro de realizar este registro?');">
							</div>

		 			</div>
		 		</div>	
							

		 			</div>
		 		</div>		 		
			 </form>
		</div>
		</div>
	</header>
</body>	