<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>
        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>
        <?php  endfor;?>
        <?php  endif;?> 
    </li>

    <li>
        <i class="fa fa-user"></i>
        <?php  if (isset($_view_params['menu9'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu9']); $i++):?>         
        <a href="<?php  echo $_view_params['menu9'][$i]['link'];?>"><?php  echo $_view_params['menu9'][$i]['title']; ?></a>
        <?php  endfor;?>
        <?php  endif;?> 
    </li>

   

    <li class="active">
        <i class="fa fa-edit"></i> Modificar datos personales
    </li>
</ol>

<body>
     <header class="header">
		<div class="row">
		    <div class="col-md-10 col-sm-offset-1" >
		    	<form  id="personuser" class="form-horizontal" action="<?php  echo BASE_URL;?>persons/updatedatospersonales" method="post">

		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-users">Usuario</h3>
		 			</div>
		 			<input type="hidden" name="id"  value="<?php echo $this->_usuario[0]['id'] ?>" >
		 			<div class="panel-body">

					<div class="form-group">




					        <div class="col-sm-6 col-sm-offset-0">
					            <strong><p id="texto"></p></strong>
					        </div>	

				            <div class="col-sm-6 col-md-offset-0">
				               <strong><p id="val"></p></strong>
				            </div>
				            						        	
					</div>

					<div class="form-group">

						<label class="col-sm-2 col-sm-offset-0">Clave</label>
						<label class="col-sm-3 col-sm-offset-4">Repita su Clave</label>
				            					        	
					</div>

					<div class="form-group">
							

							<div class="col-sm-6 col-sm-offset-0">
									<input type="password" class="form-control" name="clave" placeholder="ingrese una clave" title="clave" id="clave" required="8">	
							</div>
						
							
							<div class="col-sm-6 col-sm-offset-0">
									<input type="password" class="form-control" name="clave1" placeholder="ingrese una clave" title="clave1" id="clave1" required="8">	
							</div>							
					</div>							

					<div class="form-group">
						
						<label class="col-sm-2 col-sm-offset-0">pregunta</label>
						<label class="col-sm-2 col-sm-offset-4">respuesta</label>

				            					        	
					</div>

					<div class="form-group">
							
							<div class="col-sm-6 col-sm-offset-0">
                				<input type="text"  class="form-control" name="pregunta" placeholder="Ingrese su pregunta" title="pregunta" id="pregunta" value="<?php echo $this->_usuario[0]['pregunta'] ?>">
							</div>
							<div class="col-sm-6 col-sm-offset-0">
                				<input type="text" class="form-control" name="respuesta" placeholder="Ingrese su respuesta" title="respuesta" id="respuesta" value="<?php echo $this->_usuario[0]['respuesta'] ?>">
							</div>
						
					</div>	


					<div class="col-sm-offset-5">
						<input type="submit" value="Registrar" class="btn btn-primary" onclick=" return confirm('¿Estas seguro de realizar este registro?');">
					</div>
					

		 			</div>
		 		</div>
		 		
			 </form>
		</div>
		</div>
	</header>
</body>	