<!DOCTYPE html>
<html>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-offset-1">
      <div class="header1">
        <img src="<?php echo PUBLIC_URL; ?>img/mppe.jpg" class="img-responsive" alt="Responsive image" align="left">
        <img src="<?php echo PUBLIC_URL; ?>img/logo_200.fw.png" class="img-responsive" alt="Responsive image" align="left">
             </div>
        </div>
    </div>
 </div>
<head>
  <meta charset="utf-8">

  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <title>Sistema para el registro y control de requerimientos</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <link href="<?php echo PUBLIC_URL; ?>css/dataTables.bootstrap.css" rel="stylesheet">



    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/jquery-ui.css" />
    <link href="<?php echo PUBLIC_URL;?>css/select2.min.css" rel="stylesheet" />

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">

<!--   session get -->
  
 <?php  if((session::get('level')=='Administrador')or(session::get('level')=='Super Usuario Sistemas')or(session::get('level')=='Usuario Sistemas')or(session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>SR</b>CR</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>SIS</b>COR</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->

          <!-- Notifications: style can be found in dropdown.less -->
 

          <!-- Tasks: style can be found in dropdown.less -->

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<?php echo PUBLIC_URL; ?>img/avatar6.png" class="user-image" alt="User Image">
              <span class="hidden-xs"><?php echo  utf8_decode(Session::get('user') );?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<?php echo PUBLIC_URL; ?>img/avatar6.png" class="img-circle" alt="User Image" />

                <p>
                   Sistema para el registro y control de Requerimientos
                    
                </p>
              </li>
              <li class="divider"></li>
 
              <li class="user-footer">
                          <li>
                                    <?php  if (isset($_view_params['menu9'])):?>
                                    <?php  for ($i= 0; $i < count($_view_params['menu9']); $i++):?>         
                                    <li ><a class="fa fa-user" href="<?php  echo $_view_params['menu9'][$i]['link'];?>"> <?php  echo $_view_params['menu9'][$i]['title']; ?></a></li>        
                                    <?php  endfor;?>
                                    <?php  endif;?>
                          </li>
                          <li>
                            <a href="<?php echo $_view_params['login']['href'];?>">
                              <i class="fa <?php echo $_view_params['login']['icon'];?>"></i> 
                              <?php echo $_view_params['login']['name']; ?>
                            </a>
                          </li> 
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->

        </ul>
      </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo PUBLIC_URL; ?>AdminLTE-2.4.2/dist/img/logo-ministerio.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo  utf8_decode(Session::get('user') );?></p>
          <a href="#"><i class="fa fa-circle text-success"></i>Online</a>          
        </div>
      </div>


      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menú de Navegacion</li>
        <li class="treeview">
          <?php  if(session::get('level')==('Administrador')):?>          
          <a href="#">
            <i class="fa fa-circle-o text-yellow"></i> <span>Gestion de usuarios</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li>
              <?php  if (isset($_view_params['menu2'])):?>
              <?php  for ($i= 0; $i < count($_view_params['menu2']); $i++):?>     
              <li ><a class="fa fa-user"  href="<?php  echo $_view_params['menu2'][$i]['link'];?>"> <?php  echo $_view_params['menu2'][$i]['title']; ?></a></li>    
              <?php  endfor;?>
              <?php  endif;?> 
            </li>            
            <li>
              <?php  if (isset($_view_params['menu3'])):?>
              <?php  for ($i= 0; $i < count($_view_params['menu3']); $i++):?>     
              <li ><a class="fa fa-user"  href="<?php  echo $_view_params['menu3'][$i]['link'];?>"> <?php  echo $_view_params['menu3'][$i]['title']; ?></a></li>      
              <?php  endfor;?>
              <?php  endif;?> 
            </li>
          </ul>
          <?php  endif;?> 
        </li>

        <li class="treeview">
          <?php  if((session::get('level')=='Super Usuario Sistemas')or(session::get('level')=='Usuario Sistemas')):?>          
          <a href="#">
            <i class="fa fa-circle-o text-aqua"></i> <span>Div. Sistema</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu4'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu4']); $i++):?>         
                          <li ><a class="fa fa-file-text" href="<?php  echo $_view_params['menu4'][$i]['link'];?>"> <?php  echo $_view_params['menu4'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>

                        <li>
                          <?php  if (isset($_view_params['menu5'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu5']); $i++):?>         
                          <li ><a class="fa fa-search" href="<?php  echo $_view_params['menu5'][$i]['link'];?>"> <?php  echo $_view_params['menu5'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>

                        <li>
                          
                          <?php  if (isset($_view_params['menu6'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu6']); $i++):?>         
                          <li ><a class="fa fa-search-plus" href="<?php  echo $_view_params['menu6'][$i]['link'];?>"> <?php  echo $_view_params['menu6'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>
                         
                        </li>
          </ul>
          <?php  endif;?> 
        </li>

       <li class="treeview">
          <?php  if((session::get('level')=='Super Usuario Sistemas')or(session::get('level')=='Usuario Sistemas')):?>          
          <a href="#">
            <i class="fa fa-circle-o text-aqua"></i> <span>Reportes Sistema</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu7'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu7']); $i++):?>         
                          <li ><a class="fa fa-file-pdf-o" href="<?php  echo $_view_params['menu7'][$i]['link'];?>"> <?php  echo $_view_params['menu7'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>
                      </li>
                        <li>
                          <?php  if (isset($_view_params['menu8'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu8']); $i++):?>         
                          <li ><a class="fa fa-file-pdf-o" href="<?php  echo $_view_params['menu8'][$i]['link'];?>"> <?php  echo $_view_params['menu8'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>
                      </li>
          </ul>
          <?php  endif;?> 
        </li>


        <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>         
          <a href="#">
            <i class="fa fa-circle-o text-red"></i> <span>Div. Telematica</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">

        <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>         
          <a href="#">
            <i class="fa fa-circle-o text-orange"></i> <span>ASERV</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu14'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu14']); $i++):?>         
                          <li ><a class="fa fa-file-text" href="<?php  echo $_view_params['menu14'][$i]['link'];?>"> <?php  echo $_view_params['menu14'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>



                        <li>                          
                          <?php  if (isset($_view_params['menu15'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu15']); $i++):?>         
                          <li ><a class="fa fa-search-plus" href="<?php  echo $_view_params['menu15'][$i]['link'];?>"> <?php  echo $_view_params['menu15'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>                         
                        </li>

                        <li>                          
                          <?php  if (isset($_view_params['menu16'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu16']); $i++):?>         
                          <li ><a class="fa fa-search" href="<?php  echo $_view_params['menu16'][$i]['link'];?>"> <?php  echo $_view_params['menu16'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>                         
                        </li>

          </ul>
          <?php  endif;?> 
        </li>

        <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>         
          <a href="#">
            <i class="fa fa-circle-o text-orange"></i> <span>ASET</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu10'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu10']); $i++):?>         
                          <li ><a class="fa fa-file-text" href="<?php  echo $_view_params['menu10'][$i]['link'];?>"> <?php  echo $_view_params['menu10'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>

                        <li>
                          <?php  if (isset($_view_params['menu12'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu12']); $i++):?>         
                          <li ><a class="fa fa-search-plus" href="<?php  echo $_view_params['menu12'][$i]['link'];?>"> <?php  echo $_view_params['menu12'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>

                        <li>
                          
                          <?php  if (isset($_view_params['menu13'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu13']); $i++):?>         
                          <li ><a class="fa fa-search" href="<?php  echo $_view_params['menu13'][$i]['link'];?>"> <?php  echo $_view_params['menu13'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>
                         
                        </li>
                      
          </ul>
          <?php  endif;?> 
        </li>

          </ul>
          <?php  endif;?> 
        </li>

         <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>         
          <a href="#">
            <i class="fa fa-circle-o text-red"></i> <span>Reportes Telematica</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">

        <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>        
          <a href="#">
            <i class="fa fa-circle-o text-orange"></i> <span>ASERV</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu17'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu17']); $i++):?>         
                          <li ><a class="fa fa-file-text" href="<?php  echo $_view_params['menu17'][$i]['link'];?>"> <?php  echo $_view_params['menu17'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>



                        <li>                          
                          <?php  if (isset($_view_params['menu18'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu18']); $i++):?>         
                          <li ><a class="fa fa-search-plus" href="<?php  echo $_view_params['menu18'][$i]['link'];?>"> <?php  echo $_view_params['menu18'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>                         
                        </li>

                        <li>                          
                          <?php  if (isset($_view_params['menu21'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu21']); $i++):?>         
                          <li ><a class="fa fa-search-plus" href="<?php  echo $_view_params['menu21'][$i]['link'];?>"> <?php  echo $_view_params['menu21'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?>                         
                        </li>                        

          </ul>
          <?php  endif;?> 
        </li>

        <li class="treeview">
      <?php  if((session::get('level')=='Super Usuario Telematica')or(session::get('level')=='Usuario Telematica')):?>         
          <a href="#">
            <i class="fa fa-circle-o text-orange"></i> <span>ASET</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
                        <li>
                          <?php  if (isset($_view_params['menu19'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu19']); $i++):?>         
                          <li ><a class="fa fa-file-pdf-o" href="<?php  echo $_view_params['menu19'][$i]['link'];?>"> <?php  echo $_view_params['menu19'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>

                        <li>
                          <?php  if (isset($_view_params['menu20'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu20']); $i++):?>         
                          <li ><a class="fa fa-file-pdf-o" href="<?php  echo $_view_params['menu20'][$i]['link'];?>"> <?php  echo $_view_params['menu20'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>
                        <li>
                          <?php  if (isset($_view_params['menu22'])):?>
                          <?php  for ($i= 0; $i < count($_view_params['menu22']); $i++):?>         
                          <li ><a class="fa fa-file-pdf-o" href="<?php  echo $_view_params['menu22'][$i]['link'];?>"> <?php  echo $_view_params['menu22'][$i]['title']; ?></a></li>        
                          <?php  endfor;?>
                          <?php  endif;?> 
                        </li>                        
                      
          </ul>
          <?php  endif;?> 
        </li>

          </ul>
          <?php  endif;?> 
        </li>  

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  <div class="content-wrapper">
    <section class="content">
<?php  endif;?>